// All institution types are inferred directly from Zod schemas in institution.validator.ts
export type {
  InstitutionType,
  StudentApprovalSystem,
  MembershipFeeType,
  InstitutionRegistrationRequestStatus,
  InstitutionRegistrationInput,
  InstitutionCreationInput,
  InstitutionEntity,
  InstitutionRegistrationRequstEntity,
  InstitutionRegistrationRequstPayload,
  DepartmentEntity,
  InstitutionShiftEntity,
  InstitutionHolidaysEntity,
  HolidayType,
  AddRecurringHolidayInput,
  AddManualHolidayInput,
  DeleteInstitutionHolidayInput,
  GetInstitutionHolidaysQueryInput,
  FileAssetEntithy,
  AutomaticRegistrationKeywordEntity,
} from "./institution.validator.js";
